import Food from '../models/food';
import Category from '../shared/category';
import Size from '../shared/size';
import database from './database';

// SCRIPT INTENDED FOR RUNNING BEFORE SERVER START
const fillMenu = async () => {
	await database.connect();
	// CREATE ALL ITEM CLASSES AND SAVE

	await new Food('Miso Soup', Category.SOUP, Size.SMALL, 1.99, false).save();
	await new Food('Miso Soup', Category.SOUP, Size.LARGE, 3.99, false).save();
	await new Food('Chicken Noodle Soup', Category.SOUP, Size.SMALL, 1.99, false).save();
	await new Food('Chicken Noodle Soup', Category.SOUP, Size.LARGE, 3.99, false).save();
	await new Food('Chicken Rice Soup', Category.SOUP, Size.SMALL, 1.99, false).save();
	await new Food('Chicken Rice Soup', Category.SOUP, Size.LARGE, 3.99, false).save();
	await new Food('Egg Drop Soup', Category.SOUP, Size.SMALL, 1.99, false).save();
	await new Food('Egg Drop Soup', Category.SOUP, Size.LARGE, 3.99, false).save();
	await new Food('Wonton Soup', Category.SOUP, Size.LARGE, 1.99, false).save();
	await new Food('Wonton Soup', Category.SOUP, Size.LARGE, 3.99, false).save();
	await new Food('Asian Hot & Sour Soup', Category.SOUP, Size.SMALL, 2.99, false).save();
	await new Food('Asian Hot & Sour Soup', Category.SOUP, Size.LARGE, 4.99, false).save();
	await new Food('Chinese Hot & Sour Soup', Category.SOUP, Size.SMALL, 2.99, false).save();
	await new Food('Chinese Hot & Sour Soup', Category.SOUP, Size.LARGE, 4.99, false).save();
	await new Food('Tofu w. Vegetable Soup', Category.SOUP, Size.LARGE, 3.99, false).save();

	await new Food('Pizza Roll', Category.APPETIZER, Size.REGULAR, 1.75, false).save();
	await new Food('Egg Roll', Category.APPETIZER, Size.REGULAR, 1.5, false).save();
	await new Food('Shrimp Roll', Category.APPETIZER, Size.REGULAR, 1.6, false).save();
	await new Food('Vegetable Dumplings', Category.APPETIZER, Size.REGULAR, 4.25, false).save();
	await new Food('Fried Wonton', Category.APPETIZER, Size.REGULAR, 4.25, false).save();
	await new Food('Edamame', Category.APPETIZER, Size.REGULAR, 3.5, false).save();
	await new Food('Shumai', Category.APPETIZER, Size.REGULAR, 5.25, false).save();
	await new Food('Lumpia', Category.APPETIZER, Size.REGULAR, 2.99, false).save();
	await new Food('Gyoza', Category.APPETIZER, Size.REGULAR, 4.99, false).save();
	await new Food('Thai Calamari', Category.APPETIZER, Size.REGULAR, 5.99, false).save();
	await new Food('Shrimp Tempura', Category.APPETIZER, Size.REGULAR, 5.99, false).save();
	await new Food('Beef Negimaki', Category.APPETIZER, Size.REGULAR, 7.99, false).save();
	await new Food('Pot Stickers', Category.APPETIZER, Size.REGULAR, 4.99, false).save();
	await new Food('Crab Rangoon', Category.APPETIZER, Size.REGULAR, 4.99, false).save();
	await new Food('Chicken Fingers', Category.APPETIZER, Size.REGULAR, 5.99, false).save();
	await new Food('Chicken Wings', Category.APPETIZER, Size.SMALL, 4.99, false).save();
	await new Food('Chicken Wings', Category.APPETIZER, Size.LARGE, 8.5, false).save();
	await new Food('Baby Back Ribs', Category.APPETIZER, Size.SMALL, 8.99, false).save();
	await new Food('Baby Back Ribs', Category.APPETIZER, Size.LARGE, 17.99, false).save();
	await new Food('Wonton w. Spicy Sauce', Category.APPETIZER, Size.REGULAR, 4.25, true).save();
	await new Food('French Fries', Category.APPETIZER, Size.REGULAR, 2.99, false).save();

	await new Food('House Salad', Category.SALAD, Size.REGULAR, 3.99, false).save();
	await new Food('Seaweed Salad', Category.SALAD, Size.REGULAR, 4.99, false).save();
	await new Food('House Salad', Category.SALAD, Size.REGULAR, 4.99, false).save();

	await new Food('Roast Duck', Category.CHINESE, Size.REGULAR, 18.99, false).save();
	await new Food('Seafood Delight', Category.CHINESE, Size.REGULAR, 17.99, false).save();
	await new Food('Happy Family', Category.CHINESE, Size.REGULAR, 12.99, false).save();
	await new Food('Imperial Shrimp', Category.CHINESE, Size.REGULAR, 11.99, false).save();
	await new Food('Ta Chien Chicken', Category.CHINESE, Size.REGULAR, 11.99, true).save();
	await new Food('Shrimp & Scallop Hunan Style', Category.CHINESE, Size.REGULAR, 12.99, true).save();
	await new Food('Beef & Scallop', Category.CHINESE, Size.REGULAR, 12.99, true).save();
	await new Food('Orange Beef', Category.CHINESE, Size.REGULAR, 12.99, true).save();
	await new Food('Chicken w. Seasonal Veggies', Category.CHINESE, Size.SMALL, 5.99, false).save();
	await new Food('Chicken w. Seasonal Veggies', Category.CHINESE, Size.LARGE, 9.99, false).save();
	await new Food('Chicken w. Broccoli', Category.CHINESE, Size.SMALL, 5.99, false).save();
	await new Food('Chicken w. Broccoli', Category.CHINESE, Size.LARGE, 9.99, false).save();
	await new Food('Beef w. Broccoli', Category.CHINESE, Size.SMALL, 5.99, false).save();
	await new Food('Beef w. Broccoli', Category.CHINESE, Size.LARGE, 9.99, false).save();
	await new Food('Shrimp w. Broccoli', Category.CHINESE, Size.SMALL, 6.25, false).save();
	await new Food('Shrimp w. Broccoli', Category.CHINESE, Size.LARGE, 10.99, false).save();
	await new Food('Sweet & Sour Chicken', Category.CHINESE, Size.SMALL, 5.99, false).save();
	await new Food('Sweet & Sour Chicken', Category.CHINESE, Size.LARGE, 9.5, false).save();
	await new Food("General Tso's Chicken", Category.CHINESE, Size.SMALL, 6.99, true).save();
	await new Food("General Tso's Chicken", Category.CHINESE, Size.LARGE, 10.99, true).save();
	await new Food('Sesame Chicken', Category.CHINESE, Size.SMALL, 6.99, false).save();
	await new Food('Sesame Chicken', Category.CHINESE, Size.LARGE, 10.99, false).save();
	await new Food('Chicken w. Garlic Sauce', Category.CHINESE, Size.SMALL, 5.99, false).save();
	await new Food('Chicken w. Garlic Sauce', Category.CHINESE, Size.LARGE, 9.99, false).save();
	await new Food('Hunan Beef', Category.CHINESE, Size.SMALL, 5.99, true).save();
	await new Food('Hunan Beef', Category.CHINESE, Size.LARGE, 9.99, true).save();
	await new Food('Kung Pao Chicken', Category.CHINESE, Size.SMALL, 5.99, true).save();
	await new Food('Kung Pao Chicken', Category.CHINESE, Size.LARGE, 9.99, true).save();
	await new Food('Shrimp w. Seasonal Veggies', Category.CHINESE, Size.SMALL, 6.25, false).save();
	await new Food('Shrimp w. Seasonal Veggies', Category.CHINESE, Size.LARGE, 10.99, false).save();
	await new Food('Chicken w. Spring Beans', Category.CHINESE, Size.REGULAR, 9.99, false).save();

	await new Food('Sauteed String Beans', Category.VEGETABLE, Size.REGULAR, 8.99, false).save();
	await new Food('Seasonal Vegetables', Category.VEGETABLE, Size.REGULAR, 8.99, false).save();
	await new Food('Bean Curd Homestyle', Category.VEGETABLE, Size.REGULAR, 8.99, false).save();
	await new Food("General Tso's Tofu", Category.VEGETABLE, Size.REGULAR, 8.99, true).save();
	await new Food('Asparagus & Snow Peas', Category.VEGETABLE, Size.REGULAR, 8.99, false).save();
	await new Food('Bean Curd Szechuan Style', Category.VEGETABLE, Size.REGULAR, 8.99, true).save();

	await new Food('Spicy Lemon Grass Chicken', Category.THAI, Size.REGULAR, 11.99, true).save();
	await new Food('Spicy Lemon Grass Beef', Category.THAI, Size.REGULAR, 11.99, true).save();
	await new Food('Spicy Lemon Grass Shrimp', Category.THAI, Size.REGULAR, 13.99, true).save();
	await new Food('Spicy Lemon Grass Scallop', Category.THAI, Size.REGULAR, 13.99, true).save();
	await new Food('Mango Chicken', Category.THAI, Size.REGULAR, 11.99, false).save();
	await new Food('Mango Shrimp', Category.THAI, Size.REGULAR, 12.99, false).save();
	await new Food('Basil Chicken', Category.THAI, Size.REGULAR, 11.99, false).save();
	await new Food('Basil Beef', Category.THAI, Size.REGULAR, 12.99, false).save();
	await new Food('Basil Shrimp', Category.THAI, Size.REGULAR, 12.99, false).save();
	await new Food('Sambal Delight', Category.THAI, Size.REGULAR, 20.99, true).save();
	await new Food('Coconut Chicken', Category.THAI, Size.REGULAR, 11.99, false).save();
	await new Food('Coconut Shrimp', Category.THAI, Size.REGULAR, 12.99, false).save();
	await new Food('Thai Crispy Chicken Tender', Category.THAI, Size.REGULAR, 11.5, false).save();
	await new Food('Shrimp w. Honey Walnut', Category.THAI, Size.REGULAR, 13.99, false).save();

	await new Food('Vegetable Green Curry', Category.CURRY, Size.REGULAR, 9.5, false).save();
	await new Food('Tofu Green Curry', Category.CURRY, Size.REGULAR, 9.5, false).save();
	await new Food('Chicken Green Curry', Category.CURRY, Size.REGULAR, 10.99, false).save();
	await new Food('Beef Green Curry', Category.CURRY, Size.REGULAR, 11.99, false).save();
	await new Food('Shrimp Green Curry', Category.CURRY, Size.REGULAR, 12.99, false).save();
	await new Food('Vegetable Red Curry', Category.CURRY, Size.REGULAR, 9.5, false).save();
	await new Food('Tofu Red Curry', Category.CURRY, Size.REGULAR, 9.5, false).save();
	await new Food('Chicken Red Curry', Category.CURRY, Size.REGULAR, 10.99, false).save();
	await new Food('Beef Red Curry', Category.CURRY, Size.REGULAR, 11.99, false).save();
	await new Food('Shrimp Red Curry', Category.CURRY, Size.REGULAR, 12.99, false).save();
	await new Food('Vegetable Yellow Curry', Category.CURRY, Size.REGULAR, 9.5, false).save();
	await new Food('Tofu Yellow Curry', Category.CURRY, Size.REGULAR, 9.5, false).save();
	await new Food('Chicken Yellow Curry', Category.CURRY, Size.REGULAR, 10.99, false).save();
	await new Food('Beef Yellow Curry', Category.CURRY, Size.REGULAR, 11.99, false).save();
	await new Food('Shrimp Yellow Curry', Category.CURRY, Size.REGULAR, 12.99, false).save();

	await new Food('Plain Fried Rice', Category.RICE, Size.SMALL, 3.95, false).save();
	await new Food('Plain Fried Rice', Category.RICE, Size.LARGE, 6.95, false).save();
	await new Food('Vegetable Fried Rice', Category.RICE, Size.SMALL, 3.95, false).save();
	await new Food('Vegetable Fried Rice', Category.RICE, Size.LARGE, 6.95, false).save();
	await new Food('Pork Fried Rice', Category.RICE, Size.SMALL, 4.5, false).save();
	await new Food('Pork Fried Rice', Category.RICE, Size.LARGE, 7.5, false).save();
	await new Food('Chicken Fried Rice', Category.RICE, Size.SMALL, 4.5, false).save();
	await new Food('Chicken Fried Rice', Category.RICE, Size.LARGE, 7.5, false).save();
	await new Food('Beef Fried Rice', Category.RICE, Size.SMALL, 4.95, false).save();
	await new Food('Beef Fried Rice', Category.RICE, Size.LARGE, 8.25, false).save();
	await new Food('Shrimp Fried Rice', Category.RICE, Size.SMALL, 5.5, false).save();
	await new Food('Shrimp Fried Rice', Category.RICE, Size.LARGE, 9.0, false).save();
	await new Food('House Fried Rice', Category.RICE, Size.SMALL, 5.5, false).save();
	await new Food('House Fried Rice', Category.RICE, Size.LARGE, 9.0, false).save();
	await new Food('Basil Vegetable Fried Rice', Category.RICE, Size.SMALL, 4.5, true).save();
	await new Food('Basil Vegetable Fried Rice', Category.RICE, Size.LARGE, 7.75, true).save();
	await new Food('Basil Pork Fried Rice', Category.RICE, Size.SMALL, 4.95, true).save();
	await new Food('Basil Pork Fried Rice', Category.RICE, Size.LARGE, 7.99, true).save();
	await new Food('Basil Chicken Fried Rice', Category.RICE, Size.SMALL, 4.95, true).save();
	await new Food('Basil Chicken Fried Rice', Category.RICE, Size.LARGE, 7.99, true).save();
	await new Food('Basil Beef Fried Rice', Category.RICE, Size.SMALL, 5.25, true).save();
	await new Food('Basil Beef Fried Rice', Category.RICE, Size.LARGE, 8.99, true).save();
	await new Food('Basil Shrimp Fried Rice', Category.RICE, Size.SMALL, 5.95, true).save();
	await new Food('Basil Shrimp Fried Rice', Category.RICE, Size.LARGE, 9.99, true).save();

	await new Food('Vegatable Pad Thai', Category.NOODLE, Size.REGULAR, 7.5, true).save();
	await new Food('Chicken Pad Thai', Category.NOODLE, Size.REGULAR, 8.5, true).save();
	await new Food('Beef Pad Thai', Category.NOODLE, Size.REGULAR, 8.99, true).save();
	await new Food('Shrimp Pad Thai', Category.NOODLE, Size.REGULAR, 9.5, true).save();
	await new Food('Vegatable Yaki Udon', Category.NOODLE, Size.REGULAR, 7.5, false).save();
	await new Food('Chicken Yaki Udon', Category.NOODLE, Size.REGULAR, 8.5, false).save();
	await new Food('Beef Yaki Udon', Category.NOODLE, Size.REGULAR, 8.99, false).save();
	await new Food('Shrimp Yaki Udon', Category.NOODLE, Size.REGULAR, 9.5, false).save();
	await new Food('Vegatable Mei Fun', Category.NOODLE, Size.REGULAR, 7.5, false).save();
	await new Food('Chicken Mei Fun', Category.NOODLE, Size.REGULAR, 8.5, false).save();
	await new Food('Beef Mei Fun', Category.NOODLE, Size.REGULAR, 8.99, false).save();
	await new Food('Shrimp Mei Fun', Category.NOODLE, Size.REGULAR, 9.5, false).save();
	await new Food('Singapore Mei Fun', Category.NOODLE, Size.REGULAR, 9.95, true).save();
	await new Food('Vegetable Lo Mein', Category.NOODLE, Size.SMALL, 4.95, false).save();
	await new Food('Vegetable Lo Mein', Category.NOODLE, Size.LARGE, 7.99, false).save();
	await new Food('Chicken Lo Mein', Category.NOODLE, Size.SMALL, 4.95, false).save();
	await new Food('Chicken Lo Mein', Category.NOODLE, Size.LARGE, 7.99, false).save();
	await new Food('Beef Lo Mein', Category.NOODLE, Size.SMALL, 5.25, false).save();
	await new Food('Beef Lo Mein', Category.NOODLE, Size.LARGE, 8.5, false).save();
	await new Food('Shrimp Lo Mein', Category.NOODLE, Size.SMALL, 5.25, false).save();
	await new Food('Shrimp Lo Mein', Category.NOODLE, Size.LARGE, 8.5, false).save();

	await new Food('Hibachi Vegetable & Tofu', Category.HIBACHI, Size.REGULAR, 8.99, false).save();
	await new Food('Hibachi Chicken', Category.HIBACHI, Size.REGULAR, 9.99, false).save();
	await new Food('Hibachi Beef', Category.HIBACHI, Size.REGULAR, 10.99, false).save();
	await new Food('Hibachi Shrimp', Category.HIBACHI, Size.REGULAR, 10.99, false).save();
	await new Food('Hibachi Chicken & Shrimp', Category.HIBACHI, Size.REGULAR, 10.99, false).save();

	await new Food('Egg Roll Tray', Category.TRAY, Size.REGULAR, 26.0, false).save();
	await new Food('Chicken w. Broccoli Tray', Category.TRAY, Size.REGULAR, 29.97, false).save();
	await new Food('Chicken w. Garlic Sauce Tray', Category.TRAY, Size.REGULAR, 29.97, false).save();
	await new Food('Vegetable Lo Mein Tray', Category.TRAY, Size.REGULAR, 23.97, false).save();
	await new Food('Sweet & Sour Chicken Tray', Category.TRAY, Size.REGULAR, 29.97, false).save();
	await new Food('Pork Fried Rice Tray', Category.TRAY, Size.REGULAR, 21.75, false).save();
	await new Food("General Tso's Chicken Tray", Category.TRAY, Size.REGULAR, 32.97, true).save();

	await new Food('# Seasonal Vegetables', Category.COMBO, Size.LUNCH, 5.99, false).save();
	await new Food('# Seasonal Vegetables', Category.COMBO, Size.DINNER, 8.29, false).save();
	await new Food('# Vegetable Pad Thai', Category.COMBO, Size.LUNCH, 6.5, true).save();
	await new Food('# Vegetable Pad Thai', Category.COMBO, Size.DINNER, 8.5, true).save();
	await new Food('# Chicken Pad Thai', Category.COMBO, Size.LUNCH, 6.5, true).save();
	await new Food('# Chicken Pad Thai', Category.COMBO, Size.DINNER, 8.5, true).save();
	await new Food('# Beef Pad Thai', Category.COMBO, Size.LUNCH, 6.5, true).save();
	await new Food('# Beef Pad Thai', Category.COMBO, Size.DINNER, 8.5, true).save();
	await new Food('# Shrimp Pad Thai', Category.COMBO, Size.LUNCH, 6.5, true).save();
	await new Food('# Shrimp Pad Thai', Category.COMBO, Size.DINNER, 8.5, true).save();
	await new Food('# Vegetable Yaki Udon', Category.COMBO, Size.LUNCH, 6.5, false).save();
	await new Food('# Vegetable Yaki Udon', Category.COMBO, Size.DINNER, 8.5, false).save();
	await new Food('# Chicken Yaki Udon', Category.COMBO, Size.LUNCH, 6.5, false).save();
	await new Food('# Chicken Yaki Udon', Category.COMBO, Size.DINNER, 8.5, false).save();
	await new Food('# Beef Yaki Udon', Category.COMBO, Size.LUNCH, 6.5, false).save();
	await new Food('# Beef Yaki Udon', Category.COMBO, Size.DINNER, 8.5, false).save();
	await new Food('# Shrimp Yaki Udon', Category.COMBO, Size.LUNCH, 6.5, false).save();
	await new Food('# Shrimp Yaki Udon', Category.COMBO, Size.DINNER, 8.5, false).save();
	await new Food('# Mango Chicken', Category.COMBO, Size.LUNCH, 6.95, false).save();
	await new Food('# Mango Chicken', Category.COMBO, Size.DINNER, 8.99, false).save();
	await new Food('# Mango Shrimp', Category.COMBO, Size.LUNCH, 6.95, false).save();
	await new Food('# Mango Shrimp', Category.COMBO, Size.DINNER, 8.99, false).save();
	await new Food('# Basil Chicken', Category.COMBO, Size.LUNCH, 6.95, false).save();
	await new Food('# Basil Chicken', Category.COMBO, Size.DINNER, 8.99, false).save();
	await new Food('# Basil Beef', Category.COMBO, Size.LUNCH, 6.95, false).save();
	await new Food('# Basil Beef', Category.COMBO, Size.DINNER, 8.99, false).save();
	await new Food('# Beef Negimaki', Category.COMBO, Size.LUNCH, 8.25, false).save();
	await new Food('# Beef Negimaki', Category.COMBO, Size.DINNER, 8.99, false).save();
	await new Food('# Chicken w. Broccoli', Category.COMBO, Size.LUNCH, 5.99, false).save();
	await new Food('# Chicken w. Broccoli', Category.COMBO, Size.DINNER, 8.29, false).save();
	await new Food('# Beef w. Broccoli', Category.COMBO, Size.LUNCH, 5.99, false).save();
	await new Food('# Beef w. Broccoli', Category.COMBO, Size.DINNER, 8.29, false).save();
	await new Food('# Shrimp w. Broccoli', Category.COMBO, Size.LUNCH, 6.5, false).save();
	await new Food('# Shrimp w. Broccoli', Category.COMBO, Size.DINNER, 8.5, false).save();
	await new Food("# General Tso's Chicken", Category.COMBO, Size.LUNCH, 6.5, true).save();
	await new Food("# General Tso's Chicken", Category.COMBO, Size.DINNER, 8.5, true).save();
	await new Food('# Shrimp w. Lobster Sauce', Category.COMBO, Size.LUNCH, 6.5, false).save();
	await new Food('# Shrimp w. Lobster Sauce', Category.COMBO, Size.DINNER, 8.5, false).save();
	await new Food('# Vegetable Lo Mein', Category.COMBO, Size.LUNCH, 5.99, false).save();
	await new Food('# Vegetable Lo Mein', Category.COMBO, Size.DINNER, 8.29, false).save();
	await new Food('# Chicken Lo Mein', Category.COMBO, Size.LUNCH, 5.99, false).save();
	await new Food('# Chicken Lo Mein', Category.COMBO, Size.DINNER, 8.29, false).save();
	await new Food('# Beef Lo Mein', Category.COMBO, Size.LUNCH, 5.99, false).save();
	await new Food('# Beef Lo Mein', Category.COMBO, Size.DINNER, 8.29, false).save();
	await new Food('# Shrimp Lo Mein', Category.COMBO, Size.LUNCH, 5.99, false).save();
	await new Food('# Shrimp Lo Mein', Category.COMBO, Size.DINNER, 8.29, false).save();
	await new Food('# Sweet & Sour Chicken', Category.COMBO, Size.LUNCH, 5.99, false).save();
	await new Food('# Sweet & Sour Chicken', Category.COMBO, Size.DINNER, 8.29, false).save();
	await new Food('# Pepper Steak w. Onion', Category.COMBO, Size.LUNCH, 5.99, false).save();
	await new Food('# Pepper Steak w. Onion', Category.COMBO, Size.DINNER, 8.29, false).save();
	await new Food('# Broccoli w. Garlic Sauce', Category.COMBO, Size.LUNCH, 5.99, true).save();
	await new Food('# Broccoli w. Garlic Sauce', Category.COMBO, Size.DINNER, 8.29, true).save();
	await new Food('# Chicken w. Garlic Sauce', Category.COMBO, Size.LUNCH, 5.99, true).save();
	await new Food('# Chicken w. Garlic Sauce', Category.COMBO, Size.DINNER, 8.29, true).save();
	await new Food('# Beef w. Garlic Sauce', Category.COMBO, Size.LUNCH, 5.99, true).save();
	await new Food('# Beef w. Garlic Sauce', Category.COMBO, Size.DINNER, 8.29, true).save();
	await new Food('# Shrimp w. Garlic Sauce', Category.COMBO, Size.LUNCH, 5.99, true).save();
	await new Food('# Shrimp w. Garlic Sauce', Category.COMBO, Size.DINNER, 8.29, true).save();
	await new Food("# General Tso's Bean Curd", Category.COMBO, Size.LUNCH, 5.99, true).save();
	await new Food("# General Tso's Bean Curd", Category.COMBO, Size.DINNER, 8.29, true).save();
	await new Food('# Chicken w. Mushroom', Category.COMBO, Size.LUNCH, 5.99, false).save();
	await new Food('# Chicken w. Mushroom', Category.COMBO, Size.DINNER, 8.29, false).save();
	await new Food('# Kung Pao Chicken', Category.COMBO, Size.LUNCH, 5.99, true).save();
	await new Food('# Kung Pao Chicken', Category.COMBO, Size.DINNER, 8.29, true).save();
	await new Food('# Chicken w. Cashew Nuts', Category.COMBO, Size.LUNCH, 5.99, false).save();
	await new Food('# Chicken w. Cashew Nuts', Category.COMBO, Size.DINNER, 8.29, false).save();
	await new Food('# Sesame Chicken', Category.COMBO, Size.LUNCH, 6.5, false).save();
	await new Food('# Sesame Chicken', Category.COMBO, Size.DINNER, 8.5, false).save();
	await new Food('# Chicken Wings', Category.COMBO, Size.LUNCH, 6.5, false).save();
	await new Food('# Chicken Wings', Category.COMBO, Size.DINNER, 8.5, false).save();

	await database.end();
};

fillMenu();
